name: vibecheck
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
   - assets/icons/vibecheck_logo.png
   - assets/icons/vibecheck_logo_small.png
   - assets/icons/b.png
   - assets/icons/dashboard.png
   - assets/icons/settings.png
   - assets/icons/vault.png
   - assets/icons/wallet.png
   - assets/icons/notification.png
   - assets/icons/profile.png
   - assets/icons/calendar.png
   - assets/icons/calendar_big.png
   - assets/icons/food.png
   - assets/icons/transpo.png
   - assets/icons/fun.png
   - assets/icons/misc.png

  uses-material-design: true

  #assets:
 #   - assets/icons/


  